import os

SIMULATION_DATABASE_HOST = os.getenv("SIMULATION_DATABASE_HOST")
SIMULATION_DATABASE_PORT = os.getenv("SIMULATION_DATABASE_PORT")
SIMULATION_DATABASE_USER = os.getenv("SIMULATION_DATABASE_USER")
SIMULATION_DATABASE_PASSWORD = os.getenv("SIMULATION_DATABASE_PASSWORD")
