import os

SIMULATION_DATABASE_HOST = os.getenv("SIMULATION_DATABASE_HOST")
SIMULATION_DATABASE_PORT = os.getenv("SIMULATION_DATABASE_PORT")
SIMULATION_DATABASE_USER = os.getenv("SIMULATION_DATABASE_USER")
SIMULATION_DATABASE_PASSWORD = os.getenv("SIMULATION_DATABASE_PASSWORD")

SM_BASE_1 = os.getenv("SM_BASE_1")
TC_BASE_1 = os.getenv("TC_BASE_1")

SM_BASE_2 = os.getenv("SM_BASE_2")
TC_BASE_2 = os.getenv("TC_BASE_2")

